version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_poker
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pokerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: jupiter*
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
