package com.pokeronline.moderacion.model;

public enum MotivoSancion {
    CONDUCTA_ANTIDEPORTIVA,
    REITERACION_INFRACCIONES,
    INFRACCIONES_GRAVES,
    LENGUAJE_OBSCENO,
    ABANDONO_REITERADO,
    USO_DE_BOTS,
    COLUSION_ENTRE_JUGADORES,
    INSULTOS_O_AMENAZAS,
    NOMBRE_INAPROPIADO,
    FRAUDE_DE_FICHAS,
    MULTICUENTA,
    MANIPULACION_RESULTADOS,
    TRAMPAS_EN_PARTIDAS_PRIVADAS,
    COMPORTAMIENTO_TOXICO_EN_TORNEOS,
    DESCONEXIONES_SOSPECHOSAS,
    INACTIVIDAD_EN_PARTIDAS,
    ABUSO_DEL_CHAT,
    CONDUCTA_INADECUADA_EN_EQUIPO
}